CREATE DATABASE IF NOT EXISTS share_a_meal
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE share_a_meal;

CREATE TABLE IF NOT EXISTS `user` (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  firstName VARCHAR(100) NOT NULL,
  lastName VARCHAR(100) NOT NULL,
  street VARCHAR(150) NULL,
  city VARCHAR(100) NULL,
  emailAddress VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  phoneNumber VARCHAR(20) NOT NULL,
  isActive BOOLEAN NOT NULL DEFAULT TRUE,
  createDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updateDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_user_emailAddress (emailAddress)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS meal (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  price DECIMAL(8, 2) NOT NULL,
  dateTime DATETIME NOT NULL,
  maxAmountOfParticipants INT UNSIGNED NOT NULL,
  imageUrl VARCHAR(500) NOT NULL,
  cookId INT UNSIGNED NOT NULL,
  isActive BOOLEAN NOT NULL DEFAULT TRUE,
  isVega BOOLEAN NOT NULL DEFAULT FALSE,
  isVegan BOOLEAN NOT NULL DEFAULT FALSE,
  isToTakeHome BOOLEAN NOT NULL DEFAULT FALSE,
  allergenes VARCHAR(500) NULL,
  createDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updateDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_meal_cookId (cookId),
  CONSTRAINT fk_meal_cook
    FOREIGN KEY (cookId) REFERENCES `user` (id)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
  CONSTRAINT chk_meal_price_positive CHECK (price > 0),
  CONSTRAINT chk_meal_max_participants_positive CHECK (maxAmountOfParticipants > 0)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS meal_participants (
  mealId INT UNSIGNED NOT NULL,
  userId INT UNSIGNED NOT NULL,
  createDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (mealId, userId),
  KEY idx_meal_participants_userId (userId),
  CONSTRAINT fk_meal_participants_meal
    FOREIGN KEY (mealId) REFERENCES meal (id)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
  CONSTRAINT fk_meal_participants_user
    FOREIGN KEY (userId) REFERENCES `user` (id)
    ON UPDATE CASCADE
    ON DELETE CASCADE
) ENGINE=InnoDB;
